# Crear una lista con 5 números y mostrar el tipo de la lista y de un elemento.

lista1 = [1,2,3,4,5]

# INVESTIGAR SOBRE ARRAYS EN PYTHON, MIRAR UN VIDEO DE YOUTUBE: BUSCAR COMO: Arrays en python , mirar algun video que explique todo en pocos minutos maximo 20
# ESTE CODIGO ESTA MAL PORQUE NO PIDE USAR FUNCION SINO SOLO MOSTRAR POR CONSOLA ES DECIR HACER UN PRINT Y LISTO
# REHACER
# ESTA FUNCION NO TIENE NINGUN SENTIDO SI YA EXISTE type() como funcion NO SE CREA OTRA VEZ, ESTAS CREANDO ALGO QUE YA EXISTE SOLO PONIENDOLE TIPO EN VEZ DE TYPE
# A NIVEL LOGICO, TIENE SENTIDO? PARA PENSAR
# SI YA EXISTE UNA FUNCION NO VOLVER A CREARLA, Y SEGUIR LAS ETAPAS, ES ETAPAS DE VARIABLES NO ESTAMOS USANDO FUNCIONES ACA

print(type(lista1))

#### LEER MIS COMENTARIOS PARA ESTA DUDA

#print(tipo(lista1(1))) no entendi como mostrar el tipo de valor del elemento

# HACER UNA EXPLICACION CON COMENTARIOS, DE ARRAYS Y COMO MOSTRAR SUS VALORES, TANTO POR INDIVIDUAL COMO POR BUCLES

# ESTO LO VOY A CORREGIR, HACERLO

#####
