# CONSEJO PARA PODER ARRANCAR ESTE EJERCICIO SINO ME EQUIVOCO ES EL DE PAR E IMPAR, PENSARLO BIEN, COMO SE CONSIGUE UN PAR O IMPAR CUANDO DIVIDIS
# SU RESTO DE DIVISION DA 0, SI DA 1 O MAS ES IMPAR, FIJARSE UN VIDEO DE MATEMATICAS EN INTERNET
# PARA ENTENDERLO MEJOR, COMO SABER SI UN NUMERO ES PAR O IMPAR BUSCAR
